--SELECT cron.unschedule('ChronTrigger isOlderThanTwoWorkdays Function')
--run ^ to get rid of me

select
  cron.schedule(
    'ChronTrigger isOlderThanTwoWorkdays Function',
    '0 16 * * MON-FRI', --4pm every workday
    $$
    select
      net.http_post(
        url:='https://niwgwqnkqpfjhxvcwjdt.supabase.co/functions/v1/isOlderThanTwoWorkdays',
        headers:='{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pd2d3cW5rcXBmamh4dmN3amR0Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MjI2OTEyNiwiZXhwIjoyMDU3ODQ1MTI2fQ.FsrStTXQlcKMLpa6AcTZaFtCo-6kwdx-hnNoU2hi4pc"}'::jsonb,
        body := '{}'::jsonb
    ) as request_id;
  $$
);